# Build settings
permalink: pretty
markdown: kramdown

# Language settings
default_lang: 'en'
languages: ['en']

# Mailchimp Settings
mailchimp:
  user: 94727f91a2184787c159d7c9f
  list: 318ed85bdb
  property: group[2845][128]
  group: group_128

# data_paginate:
#   per_page: 5
#   data: 'blog'
#   path: 'blog/page:num'
#   pagination_template: 'blog/index.html'
#   sort_field: 'date'
#   sort_reverse: true

page_gen:
  - data: 'special_offers'
    template: 'offer-details'
    dir: 'offers'
  - data: 'standalone-pages'
    template: 'standalone-page-detail'
    dir: ''
  - data: 'members-only-offers'
    template: 'members-only-offers-details'
    dir: 'offers'
  # - data: 'blog'
  #   template: 'blog-details'
  #   dir: 'blog'
  - data: 'events'
    template: 'events'
    dir: 'events'

# File Handling
# include: [_pages]
exclude: [lib, config.rb, .sass-cache, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, gulpfile.js, package.json, media.json, models.json, sitemap.json]
